apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodb
  labels:
    app: prodb
spec:
  selector:
    matchLabels:
      app: prodb
  replicas: 1
  template:
    metadata:
      labels:
        app: prodb
    spec:
      containers:
        - name: prodb
          image: vprofomis/vprofiledb:V1
          args:
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: pro-db-data
          ports:
            - name: prodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      nodeSelector:
        zone: us-east-2a
      volumes:
        - name: pro-db-data
          # This AWS EBS volume must already exist.
          awsElasticBlockStore:
            volumeID: vol-0f622c0295488c484
            fsType: ext4
