apiVersion: apps/v1
kind: Deployment
metadata:
  name: promc
spec:
  selector:
    matchLabels:
      app: promc
  replicas: 1
  template:
    metadata:
      labels:
        app: promc
    spec:
      containers:
        - name: promc
          image: rabbitmq
          ports:
            - name: promc-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"