apiVersion: apps/v1
kind: Deployment
metadata:
  name: prormq
spec:
  selector:
    matchLabels:
      app: prormq
  replicas: 1
  template:
    metadata:
      labels:
        app: prormq
    spec:
      containers:
        - name: prormq
          image: rabbitmq
          ports:
            - name: prormq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"